sudo: false
dist: trusty
language: python
python:
  - 2.7
install:
  - nvm install 8
  - npm install
script: npm $TARGET
cache:
  directories:
    - node_modules
addons:
  postgresql: "9.6"

services:
  - postgresql
  - rabbitmq
env:
  matrix:
    - TARGET=test
